import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  APP_FOOTER,
  APP_NAME,
  savedBeforeRenameNote,
  APP_TAGLINE,
  BRAND,
  BRAND_NAMES_TO_CENTRALISE,
  DAR_FOOTER,
  EXPORT_FOOTER,
  PRE_BRAND_EXPORT_NAME,
  darExportName,
  darFooter,
  pageTitle,
} from '../src/index.js';

const ROOT = fileURLToPath(new URL('../../..', import.meta.url));
const BRAND_FILE = 'packages/shared/src/brand.ts';
const SCAN = ['apps', 'packages', 'package.json', 'README.md'];
const SKIP_DIRS = new Set(['node_modules', 'dist', 'coverage', '.turbo', 'vendor']);
const TEXT = /\.(ts|tsx|js|cjs|mjs|json|html|svg|scss|css|md|webmanifest)$/;

function files(path: string): string[] {
  const full = join(ROOT, path);
  if (!statSync(full, { throwIfNoEntry: false })) return [];
  if (statSync(full).isFile()) return [path];
  return readdirSync(full).flatMap((name) =>
    SKIP_DIRS.has(name) ? [] : files(relative(ROOT, join(full, name))),
  );
}

describe('Branding lives in one constant', () => {
  it('no old app name appears anywhere outside packages/shared/src/brand.ts', () => {
    const offenders: string[] = [];
    for (const f of SCAN.flatMap(files)) {
      if (f === BRAND_FILE || !TEXT.test(f) || f.endsWith('package-lock.json')) continue;
      const text = readFileSync(join(ROOT, f), 'utf8');
      for (const name of BRAND_NAMES_TO_CENTRALISE) {
        if (text.includes(name)) offenders.push(`${f}: "${name}"`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it('the rename is a single line in brand.ts', () => {
    const src = readFileSync(join(ROOT, BRAND_FILE), 'utf8');
    const flip = src.split('\n').filter((l) => l.includes('FLIP:'));
    expect(flip).toHaveLength(1);
    expect(flip[0]).toMatch(/^export const BRAND: BrandProfile = (CURRENT|OPSTRACK);/);
  });

  it('derived texts follow the constant', () => {
    expect(APP_NAME).toBe(BRAND.name);
    expect(APP_TAGLINE).toBe('by Jomerson & Grok');
    expect(EXPORT_FOOTER).toBe(`This is an automated email. Generated by ${BRAND.exportName}.`);
    expect(DAR_FOOTER).toBe(EXPORT_FOOTER);
    expect(pageTitle('My tasks')).toBe(`${APP_NAME} – My tasks`);
    expect(APP_FOOTER).toBe(`${APP_NAME} · by Jomerson & Grok`);
    expect(savedBeforeRenameNote()).toContain(`renamed to ${APP_NAME} (Oct 10, 2026)`);
    expect(pageTitle()).toBe(APP_NAME);
  });

  it('a saved DAR keeps the name it was saved with', () => {
    expect(darExportName({ exportName: 'Saved Name' })).toBe('Saved Name');
    expect(darFooter({ exportName: 'Saved Name' })).toBe(
      'This is an automated email. Generated by Saved Name.',
    );
    // Snapshots from before reports carried a name were saved under the pre-rename name.
    expect(darExportName({})).toBe(PRE_BRAND_EXPORT_NAME);
  });
});
