/**
 * Branding: the ONE place the app's name, tagline and export footer live. Every screen, the
 * browser tab, the web manifest and the DAR PDF/Excel exports read from here (a test fails if
 * the old names appear anywhere else).
 *
 * OpsTrack (Ops Pulse logo, docs/design/logo/opstrack/final) was confirmed by Jomerson on
 * 2026-10-10. The name is chosen by the single line marked FLIP below.
 */
export interface BrandProfile {
  /** Full name: sidebar brand, browser tab, login/invite/reset screens, manifest. */
  name: string;
  /** Narrow places (sidebar on small screens, manifest short_name). */
  shortName: string;
  /** Application name in exports (PDF/Excel creator and footer). */
  exportName: string;
  /** Use the full Ops Pulse lockup (logo.svg / logo-white.svg), whose artwork reads "OpsTrack". */
  lockup: boolean;
}

/** The name before OpsTrack (kept for saved DAR snapshots and the no-old-names test). */
const CURRENT: BrandProfile = {
  name: 'Implementation Tracker',
  shortName: 'Impl. Tracker',
  exportName: 'Project Activity Tracker Application',
  lockup: false,
};

/** The app name since 2026-10-10 (Ops Pulse assets). */
const OPSTRACK: BrandProfile = {
  name: 'OpsTrack',
  shortName: 'OpsTrack',
  exportName: 'OpsTrack',
  lockup: true,
};

export const BRAND: BrandProfile = OPSTRACK; // FLIP: OpsTrack confirmed by Jomerson (2026-10-10); CURRENT to revert.

/** Both profiles, for tests and previews. */
export const BRAND_PROFILES = { current: CURRENT, opstrack: OPSTRACK } as const;

export const APP_NAME = BRAND.name;
export const APP_SHORT_NAME = BRAND.shortName;
/** Always "by Jomerson & Grok" (logo README). */
export const APP_TAGLINE = 'by Jomerson & Grok';
/** The DAR export footer for a given export name. */
export const exportFooterFor = (exportName: string) =>
  `This is an automated email. Generated by ${exportName}.`;
/** Footer on every DAR export (FR-DAR-08). */
export const EXPORT_FOOTER = exportFooterFor(BRAND.exportName);
/** Browser tab (mockup v0.9.1): "OpsTrack – Page" (or just the app name). */
export const pageTitle = (page?: string) => (page ? `${APP_NAME} – ${page}` : APP_NAME);
/** Small app footer (mockup v0.9.1): "OpsTrack · by Jomerson & Grok". */
export const APP_FOOTER = `${APP_NAME} · ${APP_TAGLINE}`;
/** When the app became OpsTrack (mockup v0.9.1). */
export const RENAMED_ON = 'Oct 10, 2026';
/** Under a saved DAR that still carries the old name in its footer. */
export const savedBeforeRenameNote = () =>
  `Saved before the app was renamed to ${APP_NAME} (${RENAMED_ON}), so this copy keeps the old name in its footer, exactly as it was saved.`;
/** On the saved reports list. */
export const oldNameOnOlderCopiesNote = () =>
  `Reports saved before ${RENAMED_ON} keep "${PRE_BRAND_EXPORT_NAME}" in the footer because saved copies are never changed. New reports say "Generated by ${BRAND.exportName}".`;

/**
 * The export name of DAR snapshots saved before the snapshot stored its own branding: they were
 * saved under today's name, and keep it after a rename.
 */
export const PRE_BRAND_EXPORT_NAME = CURRENT.exportName;

/** Old names, listed only so the no-stray-names test can look for them. */
export const BRAND_NAMES_TO_CENTRALISE = [CURRENT.name, CURRENT.shortName, CURRENT.exportName];

/** Public paths of the Ops Pulse assets (apps/web/public). */
export const BRAND_ASSETS = {
  logo: '/brand/logo.svg',
  logoWhite: '/brand/logo-white.svg',
  icon: '/brand/icon.svg',
  iconWhite: '/brand/icon-white.svg',
} as const;
