import { screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import type { DarReportDto, SavedReportDto, SavedReportSummaryDto } from '@xc8/shared';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { App } from '../App';
import { api, type Route } from './m2fixtures';
import { renderAt } from './utils';

/** M6 Daily Accomplishment Report UI (doc 14 §3, §14, §15; mockup v0.8.7; QA 06 TC-R01..R10). */
afterEach(() => vi.unstubAllGlobals());

const row = (over: Partial<DarReportDto['rows'][number]> = {}): DarReportDto['rows'][number] => ({
  date: '2026-09-30',
  timeIn: '08:00 AM',
  timeOut: '12:00 PM',
  minutes: 240,
  rendered: '04:00',
  client: 'AIRSPEED INT',
  project: 'ADFS Integration to Business One',
  activityType: 'Integration',
  location: 'WFH',
  billable: 'Yes',
  module: 'ADFS Remote',
  remarks: 'Checked JAEIA Logs Issue',
  ...over,
});

const report = (over: Partial<DarReportDto> = {}): DarReportDto => ({
  user: { id: 'u1', name: 'Maria Member' },
  supervisor: { id: 'u9', name: 'Jomerson Nazaire' },
  cc: ['hr@xceler8.example'],
  from: '2026-09-30',
  to: '2026-10-02',
  shownTo: '2026-10-02',
  generatedAt: '2026-10-03T01:00:00.000Z',
  totalActivities: 2,
  totalMinutes: 307,
  totalRendered: '05:07',
  rows: [
    row(),
    row({
      timeIn: '01:00 PM',
      timeOut: '02:07 PM',
      minutes: 67,
      rendered: '01:07',
      client: '',
      project: '',
      activityType: 'Client meeting',
      billable: 'No',
      module: '',
      remarks: '<script>alert(1)</script> <img src=x onerror=alert(1)>',
    }),
  ],
  days: [
    {
      date: '2026-09-30',
      status: 'Submitted',
      reopenedBy: null,
      leave: null,
      minutes: 307,
      activities: 2,
    },
    {
      date: '2026-10-01',
      status: 'Reopened',
      reopenedBy: 'Jomerson Nazaire',
      leave: null,
      minutes: 0,
      activities: 0,
    },
    {
      date: '2026-10-02',
      status: 'Not submitted',
      reopenedBy: null,
      leave: null,
      minutes: 0,
      activities: 0,
    },
  ],
  runningExcluded: 1,
  ...over,
});

const darRoute =
  (r: DarReportDto, extra: Route = () => undefined): Route =>
  (url, init) =>
    extra(url, init) ??
    (/\/dar(\?|$)/.test(url) ? { status: 200, body: { report: r } } : undefined);

describe('TC-R01/R02/R04/R06: report preview', () => {
  it('shows the sample layout, day status and no Send button', async () => {
    api('MEMBER', darRoute(report()));
    renderAt('/dar?from=2026-09-30&to=2026-10-02', <App />);
    const view = await screen.findByTestId('dar-report');
    expect(within(view).getByText('Daily Accomplishment Report')).toBeInTheDocument();
    expect(
      within(view).getByText('Generated range: Sep 30, 2026 to Oct 2, 2026'),
    ).toBeInTheDocument();
    expect(within(view).getByText('Total Activities:').parentElement).toHaveTextContent(
      'Total Activities: 2',
    );
    const heads = within(view)
      .getAllByRole('columnheader')
      .map((h) => h.textContent);
    expect(heads).toEqual([
      'Date',
      'Time In',
      'Time Out',
      'Rendered Hrs',
      'Client Name',
      'Project Name',
      'Activity Type',
      'Location',
      'Billable',
      'Module',
      'Activity Remarks',
    ]);
    expect(within(view).getByText('08:00 AM')).toBeInTheDocument();
    expect(within(view).getByText('Total rendered hours').parentElement).toHaveTextContent('05:07');
    expect(
      within(view).getByText(
        'This is an automated email. Generated by Project Activity Tracker Application.',
      ),
    ).toBeInTheDocument();
    // TC-R10: markup in remarks is text.
    expect(
      within(view).getByText('<script>alert(1)</script> <img src=x onerror=alert(1)>'),
    ).toBeInTheDocument();
    expect(view.querySelector('script, img')).toBeNull();
    // TC-R04: day status, not part of the report.
    const status = screen.getByTestId('dar-day-status');
    expect(status).toHaveTextContent('Sep 30 Submitted');
    expect(status).toHaveTextContent('Oct 1 Reopened by Jomerson Nazaire');
    expect(status).toHaveTextContent('Oct 2 Not submitted');
    expect(status).toHaveTextContent("A running timer isn't included until you press Time out.");
    // TC-R06
    expect(screen.queryByRole('button', { name: /send/i })).not.toBeInTheDocument();
    expect(screen.getByText('Coming with Microsoft sign-in')).toBeInTheDocument();
    expect(
      screen.getByText(/Supervisor: Jomerson Nazaire · CC: hr@xceler8.example/),
    ).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Export PDF' })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Export Excel' })).toBeInTheDocument();
  });

  it('TC-R03: refuses over 31 days and From after To before asking the server', async () => {
    const fetch = api('MEMBER', darRoute(report()));
    renderAt('/dar?from=2026-09-30&to=2026-10-02', <App />);
    await screen.findByTestId('dar-report');
    const from = screen.getByLabelText('From');
    await userEvent.clear(from);
    await userEvent.type(from, '2026-08-01');
    const calls = fetch.mock.calls.length;
    await userEvent.click(screen.getByRole('button', { name: 'Preview' }));
    expect(
      await screen.findByText('The range can be up to 31 days. Pick a shorter range.'),
    ).toBeInTheDocument();
    await userEvent.clear(from);
    await userEvent.type(from, '2026-10-05');
    await userEvent.click(screen.getByRole('button', { name: 'Preview' }));
    expect(await screen.findByText('"From" must be on or before "To".')).toBeInTheDocument();
    expect(fetch.mock.calls.slice(calls).some(([u]) => String(u).includes('/dar?'))).toBe(false);
  });

  it('shows the empty state; Save report confirms with a link', async () => {
    const saved = { id: 's1' } as SavedReportDto;
    const fetch = api(
      'MEMBER',
      darRoute(
        report({ rows: [], totalActivities: 0, totalMinutes: 0, totalRendered: '00:00' }),
        (url, init) =>
          url.endsWith('/dar/saved') && init?.method === 'POST'
            ? { status: 201, body: { item: saved } }
            : undefined,
      ),
    );
    renderAt('/dar?from=2026-09-30&to=2026-10-02', <App />);
    expect(await screen.findByText('No time entries in this range')).toBeInTheDocument();
    await userEvent.click(screen.getByRole('button', { name: 'Save report' }));
    expect(await screen.findByText('View saved reports')).toHaveAttribute('href', '/dar/saved');
    const post = fetch.mock.calls.find(
      ([u, i]) => String(u).endsWith('/dar/saved') && i?.method === 'POST',
    );
    expect(JSON.parse(String(post![1]!.body))).toEqual({ from: '2026-09-30', to: '2026-10-02' });
  });
});

const summary = (over: Partial<SavedReportSummaryDto>): SavedReportSummaryDto => ({
  id: 's1',
  savedAt: '2026-10-03T01:10:00.000Z',
  from: '2026-09-30',
  to: '2026-10-02',
  totalActivities: 7,
  totalMinutes: 1130,
  totalRendered: '18:50',
  tag: 'LATEST',
  changedDates: [],
  ...over,
});

describe('TC-R07/R09: saved reports', () => {
  it('lists Latest, Earlier version and untagged overlaps; opens the read-only copy', async () => {
    const items = [
      summary({ id: 's1' }),
      summary({
        id: 's2',
        savedAt: '2026-10-02T10:20:00.000Z',
        tag: 'EARLIER',
        changedDates: ['2026-10-01'],
      }),
      summary({ id: 's3', from: '2026-10-01', tag: null }),
    ];
    api('MEMBER', (url) => {
      if (url.includes('/dar/saved/s2'))
        return { status: 200, body: { item: { ...items[1], report: report() } } };
      if (url.includes('/dar/saved')) return { status: 200, body: { items } };
      return undefined;
    });
    renderAt('/dar/saved', <App />);
    const rows = await screen.findAllByRole('row');
    expect(rows[1]).toHaveTextContent('Oct 3, 2026');
    expect(rows[1]).toHaveTextContent('Sep 30 – Oct 2');
    expect(rows[1]).toHaveTextContent('Latest');
    expect(rows[2]).toHaveTextContent('Earlier version');
    expect(rows[2]).toHaveTextContent('Changed after saving');
    expect(rows[3]).toHaveTextContent('Oct 1 – Oct 2');
    expect(rows[3]).not.toHaveTextContent(/Latest|Earlier/);
    // No edit or delete anywhere (FR-DAR-15).
    expect(screen.queryByRole('button', { name: /delete|edit/i })).not.toBeInTheDocument();
    await userEvent.click(within(rows[2]!).getByRole('button', { name: 'View' }));
    const dialog = await screen.findByRole('dialog');
    expect(within(dialog).getByText('Read-only')).toBeInTheDocument();
    expect(
      within(dialog).getByText(
        /^Saved copy from .*Later changes to your entries don't change it\.$/,
      ),
    ).toBeInTheDocument();
    expect(within(dialog).getByText(/Oct 1 was changed after this was saved/)).toBeInTheDocument();
    expect(within(dialog).getByRole('link', { name: 'Create a new report' })).toHaveAttribute(
      'href',
      '/dar?from=2026-09-30&to=2026-10-02',
    );
    expect(within(dialog).getByRole('button', { name: 'Export PDF' })).toBeInTheDocument();
    expect(within(dialog).queryByRole('button', { name: /delete|send/i })).not.toBeInTheDocument();
  });

  it('shows the empty state and the no-results state', async () => {
    api('MEMBER', (url) =>
      url.includes('/dar/saved') ? { status: 200, body: { items: [] } } : undefined,
    );
    renderAt('/dar/saved', <App />);
    expect(await screen.findByText('No saved reports yet')).toBeInTheDocument();
    await userEvent.selectOptions(screen.getByLabelText('Label'), 'LATEST');
    expect(await screen.findByText('No saved reports match these filters')).toBeInTheDocument();
    await userEvent.click(screen.getByRole('button', { name: 'Clear filters' }));
    await waitFor(() => expect(screen.getByText('No saved reports yet')).toBeInTheDocument());
  });
});
